# application-example.yml

spring:
  application:
    name: blackjack-api

  # MongoDB Reactive Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack_db
      # ⚠️ Reemplaza con tu usuario y password si estás usando autenticación

  # R2DBC MySQL Configuration (reactive)
  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack_db
    username: your_mysql_user
    password: your_mysql_password
    # ⚠️ Asegúrate de que el puerto 3306 esté abierto y la DB creada

server:
  port: 8080

# Swagger config (opcional si personalizas rutas)
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Logging (opcional)
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.mongodb.core: DEBUG
