version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      MYSQL_DATABASE: blackjack_db

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  blackjack-api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongo
    env_file:
      - .env.docker

volumes:
  mysql_data:
  mongo_data:
